substitutions:
  _APP_BUCKET_PATH: ''
  _APP_DEPLOY_URL: '/'
  _APP_BASE_HREF: '/'
  _API_BUCKET_PATH: ''
  _NG_BUILD_CONFIG: ''
steps:
- name: node:lts
  entrypoint: npm
  args: ['install']
  env:
    - 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true'

- name: node:lts
  entrypoint: npm
  args: ['install', '-g', '@angular/cli@10.2.0']

- name: 'gcr.io/cloud-builders/gcloud'
  id: version id for environment files
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/api/src/environments/environment.dev.ts
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/api/src/environments/environment.prod.ts
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/meet-app/src/environments/environment.dev.ts
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/meet-app/src/environments/environment.prod.ts

- id: build-app
  name: node:lts
  entrypoint: npm
  args: [ 'run', 'build', '--', '--configuration=${_NG_BUILD_CONFIG}', '--localize', '--deployUrl=./' ]

- id: rsync-app-to-storage
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'dist/apps/meet-app', '${_APP_BUCKET_PATH}']

- id: build-redirect-client-app
  name: node:lts
  entrypoint: npm
  args: [ 'run', 'build:redirect-client' ]

- id: rsync-app-to-storage-redirect-client-app
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'redirect-client-app', '${_APP_BUCKET_PATH}']

- id: build-api
  name: node:lts
  entrypoint: npm
  args: [ 'run', 'build', '--', 'api', '--configuration=${_NG_BUILD_CONFIG}' ]

# - name: 'gcr.io/cloud-builders/gcloud'
#   id: build output debugging
#   entrypoint: /bin/sh
#   args:
#   - '-c'
#   - |
#       ls -la
#       ls -laR dist/

- id: rsync-api-to-storage
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'dist/apps/api', '${_API_BUCKET_PATH}']

- id: never-cache-redirect-client-app
  name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'Cache-Control:no-cache, no-store, max-age=0, must-revalidate'
    - '${_APP_BUCKET_PATH}/*.*'

- id: never-cache-index-en
  name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'Cache-Control:no-cache, no-store, max-age=0, must-revalidate'
    - '${_APP_BUCKET_PATH}/en/*.*'

- id: never-cache-index-es
  name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'Cache-Control:no-cache, no-store, max-age=0, must-revalidate'
    - '${_APP_BUCKET_PATH}/es/*.*'
options:
  machineType: 'N1_HIGHCPU_8'
