substitutions:
  _APP_BUCKET_PATH: ''
  _API_BUCKET_PATH: ''
  _NG_BUILD_CONFIG: ''
steps:
- name: node:lts
  entrypoint: npm
  args: ['install']
  env:
    - 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true'

- name: node:lts
  entrypoint: npm
  args: ['install', '-g', '@angular/cli@10.2.0']

- name: 'gcr.io/cloud-builders/gcloud'
  id: version id for environment files
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
      ls -la
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/api/src/environments/environment.dev.ts
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/api/src/environments/environment.prod.ts
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/meet-app/src/environments/environment.dev.ts
      sed -i "s/APPLICATION_VERSION/${SHORT_SHA}/g" apps/meet-app/src/environments/environment.prod.ts

- name: node:lts
  entrypoint: npm
  args: [ 'run', 'ng', 'build', '${_NG_BUILD_CONFIG}', '--base-href=/www-devsandbox-static-site/' ]

- id: rsync-app-to-storage
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'dist/apps/meet-app', '${_APP_BUCKET_PATH}']

- id: rsync-api-to-storage
  name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-R', 'dist/apps/api', '${_API_BUCKET_PATH}']

- id: never-cache-index
  name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'Cache-Control:no-cache, no-store, max-age=0, must-revalidate'
    - '${_BUCKET_PATH}/index.html'
options:
  machineType: 'N1_HIGHCPU_8'
